### ISSUE TITLE
What's this repo's purpose?

### ISSUE THREAD

**Issue by zautumnz** [pkg-json/package.json#2]
What's it for? AFAICT this project isn't associated with any company (Facebook, npm) or individual developer that maintains a package manager or JS engine, so would it be more accurate to call this a styleguide, or a combined reference/documentation?

**Comment by lhorie** [comment]
I agree with @zkat that this document should not be normative.

If the goal is indeed merely documentation, it should drop things that aren't currently honored by the ecosystem, e.g. "Don't put [js](https://www.npmjs.com/package/js) or [node](https://www.npmjs.com/package/node) in the name"

Another example: "name (required)" is not true. The following package.json file is sufficient to run `npm run hello` or `yarn hello`

```json
{
  "scripts": {
    "hello": "echo hello"
  }
}
```

**Comment by jamiebuilds** [comment]
> AFAICT this project isn't associated with any company

`package.json` should not be specified by a private company.

> individual developer that maintains a package manager or JS engine

A number of tools have asked for a `package.json` spec, a spec could be developed with many stakeholders.

A short list of tools with maintainers who have asked for a `package.json` spec and who could get together to develop one:

- Node
- Yarn
- Parcel
- Webpack
- Rollup
- Lerna
- SystemJS
- Babel
- TypeScript
- jspm

I could keep going if I think a bit more, but the point is that it's needed. And it's needed by both package managers, build tools, and ecosystems that depend heavily on it.

**Comment by devongovett** [comment]
I think the goals are outlined clearly in the readme. 

First is to write down in detailed language how existing fields implemented by various tools are used. This way new tools can correctly implement support for fields used by other tools without reading their source code.

Second is to provide a process for consensus building around new fields among various tools. The point is not to stop tools from experimenting and creating their own fields. But if those tools are interested in coming to a consensus with other tool makers around a feature, this would be a good place to do so.
