### ISSUE TITLE
Crossover with stereobooster/package.json?

### ISSUE THREAD

**Issue by joshgillies** [pkg-json/package.json#3]
See https://github.com/stereobooster/package.json

cc  @stereobooster

**Comment by joshgillies** [comment]
Sorry, didn't read the history https://github.com/pkg-json/package.json#history section in the read me. Closing.

**Comment by stereobooster** [comment]
I'm ready to move my repo to your organisation. It can be eventually deprecated as soon as this repo become bigger.
