### ISSUE TITLE
Name of this repository is unfortunate

### ISSUE THREAD

**Issue by Andarist** [pkg-json/package.json#5]
I keep my cloned repositories in a single directory so I've ended up with `package.json` (directory!) in parent directory of every other project I work on and that made `yarn` to trip with

> error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".

In every project of mine - it has tried to read it as file, for some reason "escaping" the project boundary (I suspect this is normal behaviour, I just havent ever relied on that behaviour), and crashed. 

I would advise renaming it to `pkg.json` or `package.json-spec` to avoid this issue altogether.

**Comment by devongovett** [comment]
looool good bug. maybe `package-json`?

**Comment by Andarist** [comment]
Yeah, this one works too 😉

**Comment by dzek69** [comment]
Funny bug you've found @Andarist - please report it to yarn team as well :)

**Comment by Andarist** [comment]
@dzek69 I did 😉 https://github.com/yarnpkg/yarn/issues/6062

**Comment by devongovett** [comment]
renamed to `package-json`.
